### PR TITLE
Feature/18 fix typoscript loading error

### LINKED ISSUE #16: Caching footer and header
In order to get the footer and header rendered I had to set no_cache = 1 via typoscript:
[globalVar = GP:tx_web2pdf_pi1 > 0]
config.no_cache = 1
[global]

### PR DESCRIPTION
**Pull request by kpurrmann**
- #18 Get rid of error when Typoscript is missing.
- Updated doc to insert static templates.
- Should be fix #16 too

### CODE REVIEW

File: Classes/Options/ModuleOptions.php [hunk 1]
```diff
@@ -55,8 +55,11 @@ class ModuleOptions implements \TYPO3\CMS\Core\SingletonInterface {
      */
     public function initializeObject() {
         $configuration = $this->configurationManager->getConfiguration(ConfigurationManagerInterface::CONFIGURATION_TYPE_FULL_TYPOSCRIPT);
+        $settings = $configuration['plugin.']['tx_web2pdf.']['settings.'];
+        $viewSettings = $configuration['plugin.']['tx_web2pdf.']['view.'];
```
Comment (martin-helmich) [inline Classes/Options/ModuleOptions.php]: This will result in PHP notices (sth. like `Undefined index: tx_web2pdf.`) when `$configuration['plugin.']['tx_web2pdf.']['settings.']` is not set. Using `isset` instead should be safe.

Comment (kpurrmann) [inline Classes/Options/ModuleOptions.php]: thanks for hint. Edited lines.
